create table json_cache(
    _id integer primary key autoincrement,
    type text unique,
    json text not null,
    ttl integer not null,
    last_cached not null
);

create table RESERVATIONS_CACHE (
    _ID integer primary key autoincrement,
    CACHE_SOURCE text,
    CTYHOCN text not null,
    HOTEL_NAME text not null,
    HOTEL_BRAND text not null,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_ADDRESS_FORMATTED text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_KEYSHARE_SUPPRESSION boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    HOTEL_CR_FULLY_ENABLED boolean,
    HOTEL_CAMPUS_TYPE text,
    RES_CONFIRMATION_NUMBER text not null,
    RES_DKEY_SHARE_ELIGIBLE boolean,
    RES_DKEY_SHARE_COUNT integer,
    RES_FIRST_NAME text,
    RES_LAST_NAME text,
    RES_CHECKIN_DATE text not null,
    RES_CHECKOUT_DATE text not null,
    RES_CHECKIN_TIMESTAMP integer not null default 0,
    RES_CHECKOUT_TIMESTAMP integer not null default 0,
    ROOM_STAY_STATUS text not null,
    ROOM_STAY_ID text not null,
    ROOM_SEGMENT_NUMBER text not null,
    ROOM_GNR text not null,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    ROOM_AUTO_UPGRADE boolean,
    ROOM_AUTO_UPGRADE_COST float,
    ROOM_AUTO_UPGRADE_COST_FMT text,
    ROOM_TYPE_ADA_ACCESSIBLE boolean,
    ROOM_TYPE_IMAGE_URL text,
    ROOM_TYPE_ROOM_NUMBER text,
    ROOM_TYPE_ROOM_TYPE_CODE text,
    ROOM_TYPE_ROOM_TYPE_DESC text,
    ROOM_TYPE_ROOM_TYPE_NAME text,
    ROOM_TYPE_SMOKING_ROOM boolean,
    PRIOR_ROOM_TYPE_ADA_ACCESSIBLE boolean,
    PRIOR_ROOM_TYPE_IMAGE_URL text,
    PRIOR_ROOM_TYPE_ROOM_NUMBER text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_CODE text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_DESC text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_NAME text,
    PRIOR_ROOM_TYPE_SMOKING_ROOM boolean,
    HOTEL_ALLOW_OFFER boolean,
    HOTEL_OFFER_TYPE text,
    LAST_MODIFIED text not null,
    ROOM_STAY_ALLOW_UPSELL boolean,
    ROOM_STAY_UPSELL boolean,
    ROOM_STAY_UPSELL_OVER_AUTO_UPGRADE boolean,
    HOTEL_DISPLAY text,
    HOTEL_MESSAGING_LEGACY boolean,
    HOTEL_MESSAGING_KIPSU_ON boolean,
    HOTEL_MESSAGING_TILE_ON boolean,
    HOTEL_MESSAGING_EMSG_ON boolean,
    RES_LCO_TIME_OR_NULL text
);

create table RESERVATIONS_TEMP_CACHE (
    _ID integer primary key autoincrement,
    CACHE_SOURCE text,
    CTYHOCN text not null,
    HOTEL_NAME text not null,
    HOTEL_BRAND text not null,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_ADDRESS_FORMATTED text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_KEYSHARE_SUPPRESSION boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    HOTEL_CR_FULLY_ENABLED boolean,
    HOTEL_CAMPUS_TYPE text,
    RES_CONFIRMATION_NUMBER text not null,
    RES_DKEY_SHARE_ELIGIBLE boolean,
    RES_DKEY_SHARE_COUNT integer,
    RES_FIRST_NAME text,
    RES_LAST_NAME text,
    RES_CHECKIN_DATE text not null,
    RES_CHECKOUT_DATE text not null,
    RES_CHECKIN_TIMESTAMP integer not null default 0,
    RES_CHECKOUT_TIMESTAMP integer not null default 0,
    ROOM_STAY_STATUS text,
    ROOM_STAY_ID text,
    ROOM_SEGMENT_NUMBER text,
    ROOM_GNR text,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    ROOM_AUTO_UPGRADE boolean,
    ROOM_AUTO_UPGRADE_COST float,
    ROOM_AUTO_UPGRADE_COST_FMT text,
    ROOM_TYPE_ADA_ACCESSIBLE boolean,
    ROOM_TYPE_IMAGE_URL text,
    ROOM_TYPE_ROOM_NUMBER text,
    ROOM_TYPE_ROOM_TYPE_CODE text,
    ROOM_TYPE_ROOM_TYPE_DESC text,
    ROOM_TYPE_ROOM_TYPE_NAME text,
    ROOM_TYPE_SMOKING_ROOM boolean,
    PRIOR_ROOM_TYPE_ADA_ACCESSIBLE boolean,
    PRIOR_ROOM_TYPE_IMAGE_URL text,
    PRIOR_ROOM_TYPE_ROOM_NUMBER text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_CODE text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_DESC text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_NAME text,
    PRIOR_ROOM_TYPE_SMOKING_ROOM boolean,
    EXPIRATION_TIMESTAMP integer not null default 14400000,
    HOTEL_ALLOW_OFFER boolean,
    HOTEL_OFFER_TYPE text,
    LAST_MODIFIED text not null,
    ROOM_STAY_ALLOW_UPSELL boolean,
    ROOM_STAY_UPSELL boolean,
    ROOM_STAY_UPSELL_OVER_AUTO_UPGRADE boolean,
    HOTEL_DISPLAY text,
    HOTEL_MESSAGING_LEGACY boolean,
    HOTEL_MESSAGING_KIPSU_ON boolean,
    HOTEL_MESSAGING_TILE_ON boolean,
    HOTEL_MESSAGING_EMSG_ON boolean,
    RES_LCO_TIME_OR_NULL text
);
create table RESERVATIONS_TEMP_CANCELLED_CACHE (
    _ID integer primary key autoincrement,
    CACHE_SOURCE text,
    CTYHOCN text not null,
    HOTEL_NAME text not null,
    HOTEL_BRAND text not null,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_ADDRESS_FORMATTED text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_KEYSHARE_SUPPRESSION boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    HOTEL_CR_FULLY_ENABLED boolean,
    HOTEL_CAMPUS_TYPE text,
    RES_CONFIRMATION_NUMBER text not null,
    RES_DKEY_SHARE_ELIGIBLE boolean,
    RES_DKEY_SHARE_COUNT integer,
    RES_FIRST_NAME text,
    RES_LAST_NAME text,
    RES_CHECKIN_DATE text not null,
    RES_CHECKOUT_DATE text not null,
    RES_CHECKIN_TIMESTAMP integer not null default 0,
    RES_CHECKOUT_TIMESTAMP integer not null default 0,
    ROOM_STAY_STATUS text,
    ROOM_STAY_ID text,
    ROOM_SEGMENT_NUMBER text,
    ROOM_GNR text,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    ROOM_AUTO_UPGRADE boolean,
    ROOM_AUTO_UPGRADE_COST float,
    ROOM_AUTO_UPGRADE_COST_FMT text,
    ROOM_TYPE_ADA_ACCESSIBLE boolean,
    ROOM_TYPE_IMAGE_URL text,
    ROOM_TYPE_ROOM_NUMBER text,
    ROOM_TYPE_ROOM_TYPE_CODE text,
    ROOM_TYPE_ROOM_TYPE_DESC text,
    ROOM_TYPE_ROOM_TYPE_NAME text,
    ROOM_TYPE_SMOKING_ROOM boolean,
    PRIOR_ROOM_TYPE_ADA_ACCESSIBLE boolean,
    PRIOR_ROOM_TYPE_IMAGE_URL text,
    PRIOR_ROOM_TYPE_ROOM_NUMBER text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_CODE text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_DESC text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_NAME text,
    PRIOR_ROOM_TYPE_SMOKING_ROOM boolean,
    RES_CANCELLATION_NUMBER text not null,
    EXPIRATION_TIMESTAMP integer not null default 14400000,
    HOTEL_ADULT_AGE integer,
    HOTEL_ALLOW_OFFER boolean,
    HOTEL_OFFER_TYPE text,
    LAST_MODIFIED text not null,
    ROOM_STAY_ALLOW_UPSELL boolean,
    ROOM_STAY_UPSELL boolean,
    ROOM_STAY_UPSELL_OVER_AUTO_UPGRADE boolean,
    HOTEL_DISPLAY text,
    HOTEL_MESSAGING_LEGACY boolean,
    HOTEL_MESSAGING_KIPSU_ON boolean,
    HOTEL_MESSAGING_TILE_ON boolean,
    HOTEL_MESSAGING_EMSG_ON boolean,
    RES_LCO_TIME_OR_NULL text
);

create table DIGITAL_KEYS (
    _ID integer primary key autoincrement,
    RESERVATION_ID integer not null,
    LSN text not null,
    KEY_STATUS text not null,
    DKEY_PERM_TYPE text,
    DKEY_ALIAS text,
    foreign key(RESERVATION_ID) references RESERVATIONS_CACHE(_ID) ON DELETE CASCADE
);

create table KEY_SHARE_INFO_OPT_OUT (
    _ID integer primary key autoincrement,
    RES_CONFIRMATION_NUMBER text not null unique
);

create table ACTIVE_FENCES (
    _ID integer primary key autoincrement,
    RES_CONFIRMATION_NUMBER text not null unique,
    EXPIRATION long not null
);

create table PERSISTED_STAY_INFO (
    _ID integer primary key autoincrement,
    RES_CONFIRMATION_NUMBER text not null unique,
    FROM_THE_FRONT_DESK_SEEN boolean not null,
    WELCOME_MODAL_SEEN boolean not null,
    WELCOME_NOTIFICATION_SHOWN boolean not null,
    EXPIRATION long not null
);

create table PERSISTED_PROPERTY_INFO (
    _ID integer primary key autoincrement,
    PROPERTY_CODE text not null unique,
    PARKING_RELEASE_TIMES text not null,
    EXPIRATION long not null
);

create table RESERVATIONS_TEMP_CHECKIN_CACHE (
    _ID integer primary key autoincrement,
    CACHE_SOURCE text,
    CTYHOCN text,
    HOTEL_NAME text,
    HOTEL_BRAND text,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_ADDRESS_FORMATTED text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_KEYSHARE_SUPPRESSION boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    HOTEL_CR_FULLY_ENABLED boolean,
    HOTEL_CAMPUS_TYPE text,
    RES_CONFIRMATION_NUMBER text not null,
    RES_DKEY_SHARE_ELIGIBLE boolean,
    RES_DKEY_SHARE_COUNT integer,
    RES_FIRST_NAME text,
    RES_LAST_NAME text,
    RES_CHECKIN_DATE text,
    RES_CHECKOUT_DATE text,
    RES_CHECKIN_TIMESTAMP integer,
    RES_CHECKOUT_TIMESTAMP integer,
    ROOM_STAY_STATUS text,
    ROOM_STAY_ID text,
    ROOM_SEGMENT_NUMBER text,
    ROOM_GNR text,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    ROOM_AUTO_UPGRADE boolean,
    ROOM_AUTO_UPGRADE_COST float,
    ROOM_AUTO_UPGRADE_COST_FMT text,
    ROOM_TYPE_ADA_ACCESSIBLE boolean,
    ROOM_TYPE_IMAGE_URL text,
    ROOM_TYPE_ROOM_NUMBER text,
    ROOM_TYPE_ROOM_TYPE_CODE text,
    ROOM_TYPE_ROOM_TYPE_DESC text,
    ROOM_TYPE_ROOM_TYPE_NAME text,
    ROOM_TYPE_SMOKING_ROOM boolean,
    PRIOR_ROOM_TYPE_ADA_ACCESSIBLE boolean,
    PRIOR_ROOM_TYPE_IMAGE_URL text,
    PRIOR_ROOM_TYPE_ROOM_NUMBER text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_CODE text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_DESC text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_NAME text,
    PRIOR_ROOM_TYPE_SMOKING_ROOM boolean,
    LSN text,
    KEY_STATUS text,
    DKEY_PERM_TYPE text,
    DKEY_ALIAS text,
    EXPIRATION_TIMESTAMP integer,
    HOTEL_ALLOW_OFFER boolean,
    HOTEL_OFFER_TYPE text,
    LAST_MODIFIED text not null,
    ROOM_STAY_ALLOW_UPSELL boolean,
    ROOM_STAY_UPSELL boolean,
    ROOM_STAY_UPSELL_OVER_AUTO_UPGRADE boolean,
    HOTEL_DISPLAY text,
    HOTEL_MESSAGING_LEGACY boolean,
    HOTEL_MESSAGING_KIPSU_ON boolean,
    HOTEL_MESSAGING_TILE_ON boolean,
    HOTEL_MESSAGING_EMSG_ON boolean,
    RES_LCO_TIME_OR_NULL text,
    UNIQUE(RES_CONFIRMATION_NUMBER,ROOM_GNR)
);

create table RESERVATIONS_TEMP_CHECKOUT_CACHE (
    _ID integer primary key autoincrement,
    CACHE_SOURCE text,
    CTYHOCN text not null,
    HOTEL_NAME text not null,
    HOTEL_BRAND text not null,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_ADDRESS_FORMATTED text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_KEYSHARE_SUPPRESSION boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    HOTEL_CR_FULLY_ENABLED boolean,
    HOTEL_CAMPUS_TYPE text,
    RES_CONFIRMATION_NUMBER text not null,
    RES_DKEY_SHARE_ELIGIBLE boolean,
    RES_DKEY_SHARE_COUNT integer,
    RES_FIRST_NAME text,
    RES_LAST_NAME text,
    RES_CHECKIN_DATE text not null,
    RES_CHECKOUT_DATE text not null,
    RES_CHECKIN_TIMESTAMP integer not null default 0,
    RES_CHECKOUT_TIMESTAMP integer not null default 0,
    ROOM_STAY_STATUS text,
    ROOM_STAY_ID text,
    ROOM_SEGMENT_NUMBER text,
    ROOM_GNR text,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean default 1,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    ROOM_AUTO_UPGRADE boolean,
    ROOM_AUTO_UPGRADE_COST float,
    ROOM_AUTO_UPGRADE_COST_FMT text,
    ROOM_TYPE_ADA_ACCESSIBLE boolean,
    ROOM_TYPE_IMAGE_URL text,
    ROOM_TYPE_ROOM_NUMBER text,
    ROOM_TYPE_ROOM_TYPE_CODE text,
    ROOM_TYPE_ROOM_TYPE_DESC text,
    ROOM_TYPE_ROOM_TYPE_NAME text,
    ROOM_TYPE_SMOKING_ROOM boolean,
    PRIOR_ROOM_TYPE_ADA_ACCESSIBLE boolean,
    PRIOR_ROOM_TYPE_IMAGE_URL text,
    PRIOR_ROOM_TYPE_ROOM_NUMBER text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_CODE text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_DESC text,
    PRIOR_ROOM_TYPE_ROOM_TYPE_NAME text,
    PRIOR_ROOM_TYPE_SMOKING_ROOM boolean,
    EXPIRATION_TIMESTAMP integer not null default 14400000,
    HOTEL_ALLOW_OFFER boolean,
    HOTEL_OFFER_TYPE text,
    LAST_MODIFIED text not null,
    ROOM_STAY_ALLOW_UPSELL boolean,
    ROOM_STAY_UPSELL boolean,
    ROOM_STAY_UPSELL_OVER_AUTO_UPGRADE boolean,
    HOTEL_DISPLAY text,
    HOTEL_MESSAGING_LEGACY boolean,
    HOTEL_MESSAGING_KIPSU_ON boolean,
    HOTEL_MESSAGING_TILE_ON boolean,
    HOTEL_MESSAGING_EMSG_ON boolean,
    RES_LCO_TIME_OR_NULL text
);


create table BRAND_ALERT_VIEW_COUNT (
    _ID integer primary key autoincrement,
    ALERT_ID text not null unique,
    VIEW_COUNT integer not null default 1
);

create table FAVORITE_HOTELS_TABLE (
    _ID integer primary key autoincrement,
    CTYHOCN text not null unique,
    NAME text,
    RATING integer,
    EXPIRATION long not null
);

PRAGMA foreign_keys = ON;