alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_MESSAGING_LEGACY boolean;

alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_MESSAGING_KIPSU_ON boolean;

alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_MESSAGING_TILE_ON boolean;

alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_MESSAGING_EMSG_ON boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_MESSAGING_LEGACY boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_MESSAGING_KIPSU_ON boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_MESSAGING_TILE_ON boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_MESSAGING_EMSG_ON boolean;

alter table RESERVATIONS_TEMP_CHECKOUT_CACHE ADD COLUMN HOTEL_MESSAGING_LEGACY boolean;

alter table RESERVATIONS_TEMP_CHECKOUT_CACHE ADD COLUMN HOTEL_MESSAGING_KIPSU_ON boolean;

alter table RESERVATIONS_TEMP_CHECKOUT_CACHE ADD COLUMN HOTEL_MESSAGING_TILE_ON boolean;

alter table RESERVATIONS_TEMP_CHECKOUT_CACHE ADD COLUMN HOTEL_MESSAGING_EMSG_ON boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_MESSAGING_LEGACY boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_MESSAGING_KIPSU_ON boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_MESSAGING_TILE_ON boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_MESSAGING_EMSG_ON boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN HOTEL_MESSAGING_LEGACY boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN HOTEL_MESSAGING_KIPSU_ON boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN HOTEL_MESSAGING_TILE_ON boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN HOTEL_MESSAGING_EMSG_ON boolean;
