alter table RESERVATIONS_CACHE ADD COLUMN ROOM_STAY_ALLOW_UPSELL boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN ROOM_STAY_ALLOW_UPSELL boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN ROOM_STAY_ALLOW_UPSELL boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN ROOM_STAY_ALLOW_UPSELL boolean;

alter table RESERVATIONS_TEMP_CHECKOUT_CACHE ADD COLUMN ROOM_STAY_ALLOW_UPSELL boolean;