alter table PERSISTED_STAY_INFO rename to PERSISTED_STAY_INFO_BACKUP;

create table PERSISTED_STAY_INFO (
    _ID integer primary key autoincrement,
    RES_CONFIRMATION_NUMBER text not null unique,
    FROM_THE_FRONT_DESK_SEEN boolean not null,
    WELCOME_MODAL_SEEN boolean not null,
    WELCOME_NOTIFICATION_SHOWN boolean not null,
    EXPIRATION long not null
);

insert into PERSISTED_STAY_INFO (
    RES_CONFIRMATION_NUMBER,
    FROM_THE_FRONT_DESK_SEEN,
    WELCOME_MODAL_SEEN,
    WELCOME_NOTIFICATION_SHOWN,
    EXPIRATION
) select RES_CONFIRMATION_NUMBER,
    FROM_THE_FRONT_DESK_SEEN,
    WELCOME_MODAL_SEEN,
    WELCOME_NOTIFICATION_SHOWN,
    EXPIRATION from PERSISTED_STAY_INFO_BACKUP;

drop table PERSISTED_STAY_INFO_BACKUP;