alter table RESERVATIONS_CACHE ADD COLUMN ROOM_DIGITAL_CHECKOUT_READY boolean;
alter table RESERVATIONS_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_TITLE text;
alter table RESERVATIONS_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_MESSAGE text;
alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_ALLOW_DCO boolean;
alter table RESERVATIONS_CACHE ADD COLUMN ROOM_CHECKED_OUT boolean;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN ROOM_DIGITAL_CHECKOUT_READY boolean;
alter table RESERVATIONS_TEMP_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_TITLE text;
alter table RESERVATIONS_TEMP_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_MESSAGE text;
alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_ALLOW_DCO boolean;
alter table RESERVATIONS_TEMP_CACHE ADD COLUMN ROOM_CHECKED_OUT boolean;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN ROOM_DIGITAL_CHECKOUT_READY boolean;
alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_TITLE text;
alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_MESSAGE text;
alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_ALLOW_DCO boolean;
alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN ROOM_CHECKED_OUT boolean;

alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN ROOM_DIGITAL_CHECKOUT_READY boolean;
alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_TITLE text;
alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN ROOM_STATUS_NOTIFICATION_MESSAGE text;
alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN HOTEL_ALLOW_DCO boolean;
alter table RESERVATIONS_TEMP_CHECKIN_CACHE ADD COLUMN ROOM_CHECKED_OUT boolean;

create table IF NOT EXISTS RESERVATIONS_TEMP_CHECKOUT_CACHE (
    _ID integer primary key autoincrement,
    CTYHOCN text not null,
    HOTEL_NAME text not null,
    HOTEL_BRAND text not null,
    HOTEL_SUB_CODE text,
    HOTEL_ADDRESS_LINE1 text,
    HOTEL_ADDRESS_CITY text,
    HOTEL_ADDRESS_REGION text,
    HOTEL_ADDRESS_POSTALCODE text,
    HOTEL_ADDRESS_COUNTRYCODE text,
    HOTEL_ADDRESS_BUILDINGNUMBER text,
    HOTEL_SUPPORT_RUA boolean,
    HOTEL_SUPPORT_NOR1 boolean,
    HOTEL_CURRENCY text,
    HOTEL_PHONE text,
    HOTEL_URL text,
    HOTEL_LATITUDE text,
    HOTEL_LONGITUDE text,
    HOTEL_CHECKIN_TIME text,
    HOTEL_CHECKOUT_TIME text,
    HOTEL_S2R_FLAG text,
    HOTEL_SECONDARY_IMAGE_URL text,
    HOTEL_IMAGE_URL text,
    HOTEL_GMTHOURS float,
    HOTEL_ALLOW_DCO boolean,
    HOTEL_CR_ENABLED boolean,
    RES_CONFIRMATION_NUMBER text not null,
    RES_CHECKIN_DATE text not null,
    RES_CHECKOUT_DATE text not null,
    RES_CHECKIN_TIMESTAMP integer not null default 0,
    RES_CHECKOUT_TIMESTAMP integer not null default 0,
    ROOM_STAY_STATUS text,
    ROOM_STAY_ID text,
    ROOM_SEGMENT_NUMBER text,
    ROOM_GNR text,
    ROOM_ROOM_TYPE text,
    ROOM_RATE_PLAN text,
    ROOM_ADULTS integer,
    ROOM_CHILDREN integer,
    ROOM_SUPPORT_RUA boolean,
    ROOM_SUPPORT_NOR1 boolean,
    ROOM_IN_HOUSE boolean,
    ROOM_DIGITAL_CHECKOUT_READY boolean,
    ROOM_CHECKED_OUT boolean default 1,
    ROOM_STATUS_NOTIFICATION_TITLE text,
    ROOM_STATUS_NOTIFICATION_MESSAGE text,
    ROOM_STRAIGHT_TO_ROOM boolean,
    ROOM_DIGITAL_KEY_OPTIN boolean,
    ROOM_DIGITAL_KEY_ELIGIBLE boolean,
    ROOM_DKEY_PARKING_ELIGIBLE boolean,
    ROOM_CHECKIN_STATUS text,
    ROOM_CHECKIN_FAILURE_REASON text,
    ROOM_CHECKIN_ROOM_ASSIGNED text,
    ROOM_CHECKIN_REQUEST_ROOM_NUMBER text,
    EXPIRATION_TIMESTAMP integer not null default 14400000,
    LAST_MODIFIED text not null
);

create table IF NOT EXISTS CHECKOUT_NOTIFICATIONS (
    _ID integer primary key autoincrement,
    CHECKOUT_CTYHOCN text,
    CONFIRMATION_NUMBER text,
    LEARN_MORE_TIME integer,
    LEARN_MORE_SEEN boolean,
    AVAILABLE_SEEN_TIME integer,
    AVAILABLE_SEEN boolean,
    EXPIRATION_TIMESTAMP integer,
    CTYHOCN_CONFIRMATION_NUMBER text unique
);