alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_URL text;
alter table RESERVATIONS_CACHE ADD COLUMN HOTEL_SECONDARY_IMAGE_URL text;

alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_URL text;
alter table RESERVATIONS_TEMP_CACHE ADD COLUMN HOTEL_SECONDARY_IMAGE_URL text;

alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_URL text;
alter table RESERVATIONS_TEMP_CANCELLED_CACHE ADD COLUMN HOTEL_SECONDARY_IMAGE_URL text;